services:
  chat:
    image: matrixdotorg/synapse:v1.141.0
    container_name: chat
    restart: always
    command: ["run"]
    ports:
      - "127.0.0.1:8008:8008" # Listen only on localhost internally
    volumes:
      - chat_data:/data
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    # ports: 5432:5432 ကို ဖြုတ်လိုက်ပါ။ internal network ကနေ chat က လှမ်းခေါ်လို့ရပါတယ်။
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: chat-user
      POSTGRES_PASSWORD: P@ss3ord # Production Password သုံးပါ
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-admin
    restart: always
    ports:
      - "127.0.0.1:3003:80" # Nginx in container uses port 80
    # volumes, tty, stdin_open တွေ အကုန်ဖြုတ်လိုက်ပါ၊ production မှာ မလိုတော့ပါ။
    depends_on:
      - chat

volumes:
  chat_data:
  postgres_data: