services:
  chat:
    image: matrixdotorg/synapse:v1.141.0
    container_name: chat
    restart: always
    command: ["run"]
    environment:
      - SYNAPSE_LOG_LEVEL=WARNING
    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - chat_data:/data
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: chat-user
      POSTGRES_PASSWORD: P@ss3ord
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chat-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-admin
    restart: always
    ports:
      - "127.0.0.1:3003:80"
    depends_on:
      - chat

volumes:
  chat_data:
  postgres_data:
